GET http://localhost:3000/users

###

GET http://localhost:3000/users/12

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Sam",
    "lastName": "Jones"
}

###

DELETE http://localhost:3000/users/60e2048301fe735e5474deaa